### ISSUE TITLE
Sign up (email, password, first name, surname, UserType) 

### ISSUE THREAD

**Issue by nachillas** [nachillas/eTeacher#2]
Pending: 
1)Forward to profile page.
2) Session management.
3) Register button (τοποθέτηση στο τέλος του μενού).
4) Validation user's credentials.

**Comment by cgiamp** [comment]
3) ΟΚ.

**Comment by cgiamp** [comment]
2) θέλει LoginInterceptor δε μου έχει δουλέψει ακόμη.
2)OK

**Comment by nachillas** [comment]
4) Validate --> Έλεγχος μοναδικότητας mail και user name, εμφάνιση αντίστοιχου error.

**Comment by nachillas** [comment]
1)Forward to profile page. + Validation of common username.
