### ISSUE TITLE
Log in (Username, Email, password)

### ISSUE THREAD

**Issue by nachillas** [nachillas/eTeacher#3]
1) Check user credentials by email and password. 
2) Session management
3) Λήψη των υπολοίπων attributes από τη βάση ώστε να εμφανίζονται στο profile του χρήστη.
4) Προώθηση στο προφίλ του χρήστη.(ανάλογα με το user type).

**Comment by cgiamp** [comment]
1) 21.9.16 - κανει auth με το email & password. Αποθηκεύει στο session το Email. 
[e-teacher_DAY_16 me neo index_kanei auth me to email.zip](https://github.com/nachillas/eTeacher/files/484897/e-teacher_DAY_16.me.neo.index_kanei.auth.me.to.email.zip) [ Netbeans Project ]

**Comment by cgiamp** [comment]
2) 23.9.16 - To session management το κάνει αυτόματα το Hibernate. Έβαλα μετά το login να σώζει όλο το αντικείμενο user μέσα στο session. **Αυτό που δεν έχω τελειώσει είναι η περίπτωση που ο χρήστης κλείσει τη σελίδα χωρίς logout να μπορεί να ξαναμπεί χωρίς credentials.** **XRHSTOS**

3) 23.9.16 - Τα υπόλοιπα attributes του χρήστη απο τη βάση μπήκαν στο session.

4) 23.9.16 - [OK] - Ο χρήστης μετά το Login προωθείται ανάλογα με τον τύπο του στον ανάλογο φάκελο (contributor, admin, customer) στο /profile.jsp. **Πρέπει να χρησιμοποιηθούν Interceptors για να κόψουμε το direct link σε αυτά τα URL που θέλουν authorization.**

4)UPDATE 14.10.16 - Δημιουργήθηκε inteceptor που ανακατευθύνει τα direct actions url's σε χρήστες που δεν είναι logged in.

2)UPDATE 14.10.16 - Auto Log In from session OK. {AutoLoginInterceptor}

**Comment by cgiamp** [comment]
cgbgdn
