### ISSUE TITLE
Εύη Issues - Due Date : 26/09

### ISSUE THREAD

**Issue by nachillas** [nachillas/eTeacher#9]
- Aνάλυση πιέσεων στο μοντέλο του Porter, Κεφ. 7 (Νίκος)
- Κεφάλαιο 4,5 - Αρχιτεκτονική (Χρήστος)
- Κεφ. 10 
- Βιβλιογραφία.

**Comment by cgiamp** [comment]
Κεφάλαιο 4+5 ΟΚ. + βιβλιογραφία ΟΚ.

**Comment by nachillas** [comment]
Ανάλυση πιέσεων, κεφάλαια 7 και 10 ΟΚ.
